export interface University {
  id: string;
  name: string;
  shortName: string;
  /** Canvas subdomain, e.g. "ou" → canvas.ou.edu  OR full domain */
  canvasDomain: string;
  primaryColor: string;    // HEX — main brand color
  secondaryColor: string;  // HEX — accent / background tint
  textOnPrimary: string;   // HEX — readable text on primaryColor background
  conference?: string;
}

export const UNIVERSITIES: University[] = [
  // ─── Big 12 ───────────────────────────────────────────────────────────────
  {
    id: 'ou',
    name: 'University of Oklahoma',
    shortName: 'OU',
    canvasDomain: 'canvas.ou.edu',
    primaryColor: '#841617',
    secondaryColor: '#F5F0E8',
    textOnPrimary: '#FFFDF7',
    conference: 'SEC',
  },
  {
    id: 'osu',
    name: 'Oklahoma State University',
    shortName: 'OSU',
    canvasDomain: 'canvas.okstate.edu',
    primaryColor: '#FF6600',
    secondaryColor: '#FFF4EB',
    textOnPrimary: '#1A0800',
    conference: 'Big 12',
  },
  {
    id: 'ut',
    name: 'University of Texas at Austin',
    shortName: 'UT Austin',
    canvasDomain: 'utexas.instructure.com',
    primaryColor: '#BF5700',
    secondaryColor: '#FFF5EC',
    textOnPrimary: '#FFFFFF',
    conference: 'SEC',
  },
  {
    id: 'tamu',
    name: 'Texas A&M University',
    shortName: 'Texas A&M',
    canvasDomain: 'canvas.tamu.edu',
    primaryColor: '#500000',
    secondaryColor: '#FFF5F5',
    textOnPrimary: '#FFFFFF',
    conference: 'SEC',
  },
  {
    id: 'kansas',
    name: 'University of Kansas',
    shortName: 'KU',
    canvasDomain: 'canvas.ku.edu',
    primaryColor: '#0051A3',
    secondaryColor: '#EDF4FF',
    textOnPrimary: '#FFFFFF',
    conference: 'Big 12',
  },
  {
    id: 'kstate',
    name: 'Kansas State University',
    shortName: 'K-State',
    canvasDomain: 'k-state.instructure.com',
    primaryColor: '#512888',
    secondaryColor: '#F3EEFF',
    textOnPrimary: '#FFFFFF',
    conference: 'Big 12',
  },
  {
    id: 'baylor',
    name: 'Baylor University',
    shortName: 'Baylor',
    canvasDomain: 'canvas.baylor.edu',
    primaryColor: '#003015',
    secondaryColor: '#F0FFF4',
    textOnPrimary: '#FFCA3A',
    conference: 'Big 12',
  },
  {
    id: 'tcu',
    name: 'Texas Christian University',
    shortName: 'TCU',
    canvasDomain: 'tcu.instructure.com',
    primaryColor: '#4D1979',
    secondaryColor: '#F5EEFF',
    textOnPrimary: '#FFFFFF',
    conference: 'Big 12',
  },
  // ─── SEC ──────────────────────────────────────────────────────────────────
  {
    id: 'alabama',
    name: 'University of Alabama',
    shortName: 'Alabama',
    canvasDomain: 'bama.instructure.com',
    primaryColor: '#9E1B32',
    secondaryColor: '#FFF0F2',
    textOnPrimary: '#FFFFFF',
    conference: 'SEC',
  },
  {
    id: 'lsu',
    name: 'Louisiana State University',
    shortName: 'LSU',
    canvasDomain: 'lsu.instructure.com',
    primaryColor: '#461D7C',
    secondaryColor: '#F6F0FF',
    textOnPrimary: '#FDD023',
    conference: 'SEC',
  },
  {
    id: 'georgia',
    name: 'University of Georgia',
    shortName: 'UGA',
    canvasDomain: 'uga.instructure.com',
    primaryColor: '#BA0C2F',
    secondaryColor: '#FFF0F3',
    textOnPrimary: '#FFFFFF',
    conference: 'SEC',
  },
  {
    id: 'florida',
    name: 'University of Florida',
    shortName: 'UF',
    canvasDomain: 'ufl.instructure.com',
    primaryColor: '#003087',
    secondaryColor: '#EDF3FF',
    textOnPrimary: '#FA4616',
    conference: 'SEC',
  },
  {
    id: 'tennessee',
    name: 'University of Tennessee',
    shortName: 'Tennessee',
    canvasDomain: 'utk.instructure.com',
    primaryColor: '#FF8200',
    secondaryColor: '#FFF3E6',
    textOnPrimary: '#FFFFFF',
    conference: 'SEC',
  },
  {
    id: 'auburn',
    name: 'Auburn University',
    shortName: 'Auburn',
    canvasDomain: 'auburn.instructure.com',
    primaryColor: '#03244D',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#E87722',
    conference: 'SEC',
  },
  // ─── Big Ten ──────────────────────────────────────────────────────────────
  {
    id: 'michigan',
    name: 'University of Michigan',
    shortName: 'Michigan',
    canvasDomain: 'umich.instructure.com',
    primaryColor: '#00274C',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#FFCB05',
    conference: 'Big Ten',
  },
  {
    id: 'ohio-state',
    name: 'Ohio State University',
    shortName: 'Ohio State',
    canvasDomain: 'osu.instructure.com',
    primaryColor: '#BB0000',
    secondaryColor: '#FFF0F0',
    textOnPrimary: '#FFFFFF',
    conference: 'Big Ten',
  },
  {
    id: 'penn-state',
    name: 'Penn State University',
    shortName: 'Penn State',
    canvasDomain: 'psu.instructure.com',
    primaryColor: '#041E42',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#FFFFFF',
    conference: 'Big Ten',
  },
  {
    id: 'michigan-state',
    name: 'Michigan State University',
    shortName: 'MSU',
    canvasDomain: 'msu.instructure.com',
    primaryColor: '#18453B',
    secondaryColor: '#EDFAF5',
    textOnPrimary: '#FFFFFF',
    conference: 'Big Ten',
  },
  {
    id: 'wisconsin',
    name: 'University of Wisconsin',
    shortName: 'Wisconsin',
    canvasDomain: 'canvas.wisc.edu',
    primaryColor: '#C5050C',
    secondaryColor: '#FFF0F0',
    textOnPrimary: '#FFFFFF',
    conference: 'Big Ten',
  },
  {
    id: 'iowa',
    name: 'University of Iowa',
    shortName: 'Iowa',
    canvasDomain: 'uiowa.instructure.com',
    primaryColor: '#FFCD00',
    secondaryColor: '#FFFBE6',
    textOnPrimary: '#000000',
    conference: 'Big Ten',
  },
  {
    id: 'minnesota',
    name: 'University of Minnesota',
    shortName: 'Minnesota',
    canvasDomain: 'canvas.umn.edu',
    primaryColor: '#7A0019',
    secondaryColor: '#FFF0F3',
    textOnPrimary: '#FFCC33',
    conference: 'Big Ten',
  },
  // ─── ACC ──────────────────────────────────────────────────────────────────
  {
    id: 'unc',
    name: 'University of North Carolina',
    shortName: 'UNC',
    canvasDomain: 'unc.instructure.com',
    primaryColor: '#4B9CD3',
    secondaryColor: '#EBF6FF',
    textOnPrimary: '#FFFFFF',
    conference: 'ACC',
  },
  {
    id: 'duke',
    name: 'Duke University',
    shortName: 'Duke',
    canvasDomain: 'canvas.duke.edu',
    primaryColor: '#00356B',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#FFFFFF',
    conference: 'ACC',
  },
  {
    id: 'clemson',
    name: 'Clemson University',
    shortName: 'Clemson',
    canvasDomain: 'clemson.instructure.com',
    primaryColor: '#F56600',
    secondaryColor: '#FFF3E6',
    textOnPrimary: '#FFFFFF',
    conference: 'ACC',
  },
  {
    id: 'nc-state',
    name: 'North Carolina State University',
    shortName: 'NC State',
    canvasDomain: 'ncsu.instructure.com',
    primaryColor: '#CC0000',
    secondaryColor: '#FFF0F0',
    textOnPrimary: '#FFFFFF',
    conference: 'ACC',
  },
  {
    id: 'virginia',
    name: 'University of Virginia',
    shortName: 'UVA',
    canvasDomain: 'uva.instructure.com',
    primaryColor: '#232D4B',
    secondaryColor: '#EAECF5',
    textOnPrimary: '#E57200',
    conference: 'ACC',
  },
  {
    id: 'fsu',
    name: 'Florida State University',
    shortName: 'FSU',
    canvasDomain: 'fsu.instructure.com',
    primaryColor: '#782F40',
    secondaryColor: '#FFF0F3',
    textOnPrimary: '#CEB888',
    conference: 'ACC',
  },
  // ─── Pac-12 / Others ──────────────────────────────────────────────────────
  {
    id: 'usc',
    name: 'University of Southern California',
    shortName: 'USC',
    canvasDomain: 'usc.instructure.com',
    primaryColor: '#990000',
    secondaryColor: '#FFF0F0',
    textOnPrimary: '#FFCC00',
    conference: 'Big Ten',
  },
  {
    id: 'ucla',
    name: 'University of California, Los Angeles',
    shortName: 'UCLA',
    canvasDomain: 'bruinlearn.ucla.edu',
    primaryColor: '#2D68C4',
    secondaryColor: '#EAF2FF',
    textOnPrimary: '#F2A900',
    conference: 'Big Ten',
  },
  {
    id: 'cal',
    name: 'UC Berkeley',
    shortName: 'Cal',
    canvasDomain: 'bcourses.berkeley.edu',
    primaryColor: '#003262',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#FDB515',
    conference: 'ACC',
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    shortName: 'Stanford',
    canvasDomain: 'canvas.stanford.edu',
    primaryColor: '#8C1515',
    secondaryColor: '#FFF0F0',
    textOnPrimary: '#FFFFFF',
    conference: 'ACC',
  },
  {
    id: 'washington',
    name: 'University of Washington',
    shortName: 'UW',
    canvasDomain: 'canvas.uw.edu',
    primaryColor: '#4B2E83',
    secondaryColor: '#F3EEFF',
    textOnPrimary: '#B7A57A',
    conference: 'Big Ten',
  },
  {
    id: 'oregon',
    name: 'University of Oregon',
    shortName: 'Oregon',
    canvasDomain: 'canvas.uoregon.edu',
    primaryColor: '#154733',
    secondaryColor: '#EDFAF5',
    textOnPrimary: '#FEE123',
    conference: 'Big Ten',
  },
  {
    id: 'arizona-state',
    name: 'Arizona State University',
    shortName: 'ASU',
    canvasDomain: 'canvas.asu.edu',
    primaryColor: '#8C1D40',
    secondaryColor: '#FFF0F4',
    textOnPrimary: '#FFC627',
    conference: 'Big 12',
  },
  {
    id: 'colorado',
    name: 'University of Colorado Boulder',
    shortName: 'CU Boulder',
    canvasDomain: 'canvas.colorado.edu',
    primaryColor: '#CFB87C',
    secondaryColor: '#FFFCF0',
    textOnPrimary: '#000000',
    conference: 'Big 12',
  },
  {
    id: 'utah',
    name: 'University of Utah',
    shortName: 'Utah',
    canvasDomain: 'utah.instructure.com',
    primaryColor: '#CC0000',
    secondaryColor: '#FFF0F0',
    textOnPrimary: '#FFFFFF',
    conference: 'Big 12',
  },
  // ─── Ivy + Elite ──────────────────────────────────────────────────────────
  {
    id: 'harvard',
    name: 'Harvard University',
    shortName: 'Harvard',
    canvasDomain: 'canvas.harvard.edu',
    primaryColor: '#A51C30',
    secondaryColor: '#FFF0F2',
    textOnPrimary: '#FFFFFF',
  },
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    shortName: 'MIT',
    canvasDomain: 'canvas.mit.edu',
    primaryColor: '#A31F34',
    secondaryColor: '#FFF0F2',
    textOnPrimary: '#FFFFFF',
  },
  {
    id: 'yale',
    name: 'Yale University',
    shortName: 'Yale',
    canvasDomain: 'canvas.yale.edu',
    primaryColor: '#00356B',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#FFFFFF',
  },
  {
    id: 'princeton',
    name: 'Princeton University',
    shortName: 'Princeton',
    canvasDomain: 'canvas.princeton.edu',
    primaryColor: '#E77500',
    secondaryColor: '#FFF4E6',
    textOnPrimary: '#FFFFFF',
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    shortName: 'Columbia',
    canvasDomain: 'courseworks2.columbia.edu',
    primaryColor: '#003DA5',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#FFFFFF',
  },
  {
    id: 'notre-dame',
    name: 'University of Notre Dame',
    shortName: 'Notre Dame',
    canvasDomain: 'canvas.nd.edu',
    primaryColor: '#0C2340',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#C99700',
    conference: 'ACC',
  },
  // ─── Other popular ────────────────────────────────────────────────────────
  {
    id: 'purdue',
    name: 'Purdue University',
    shortName: 'Purdue',
    canvasDomain: 'purdue.instructure.com',
    primaryColor: '#CEB888',
    secondaryColor: '#FFFCF0',
    textOnPrimary: '#000000',
    conference: 'Big Ten',
  },
  {
    id: 'indiana',
    name: 'Indiana University',
    shortName: 'IU',
    canvasDomain: 'canvas.iu.edu',
    primaryColor: '#990000',
    secondaryColor: '#FFF0F0',
    textOnPrimary: '#FFFFFF',
    conference: 'Big Ten',
  },
  {
    id: 'virginia-tech',
    name: 'Virginia Tech',
    shortName: 'VT',
    canvasDomain: 'canvas.vt.edu',
    primaryColor: '#861F41',
    secondaryColor: '#FFF0F4',
    textOnPrimary: '#E5751F',
    conference: 'ACC',
  },
  {
    id: 'pitt',
    name: 'University of Pittsburgh',
    shortName: 'Pitt',
    canvasDomain: 'canvas.pitt.edu',
    primaryColor: '#003594',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#FFB81C',
    conference: 'ACC',
  },
  {
    id: 'miami',
    name: 'University of Miami',
    shortName: 'Miami',
    canvasDomain: 'canvas.miami.edu',
    primaryColor: '#005030',
    secondaryColor: '#EDFAF5',
    textOnPrimary: '#F47321',
    conference: 'ACC',
  },
  {
    id: 'tulsa',
    name: 'University of Tulsa',
    shortName: 'TU',
    canvasDomain: 'canvas.utulsa.edu',
    primaryColor: '#003D79',
    secondaryColor: '#E8F0FF',
    textOnPrimary: '#C8A84B',
  },
  {
    id: 'other',
    name: 'Other / Not Listed',
    shortName: 'Other',
    canvasDomain: '',
    primaryColor: '#5B4FE8',
    secondaryColor: '#EEF0FF',
    textOnPrimary: '#FFFFFF',
  },
];

export function findUniversity(id: string): University | undefined {
  return UNIVERSITIES.find((u) => u.id === id);
}

export function searchUniversities(query: string): University[] {
  const q = query.toLowerCase().trim();
  if (!q) return UNIVERSITIES;
  return UNIVERSITIES.filter(
    (u) =>
      u.name.toLowerCase().includes(q) ||
      u.shortName.toLowerCase().includes(q) ||
      u.canvasDomain.toLowerCase().includes(q),
  );
}
